services:
  backend:
    build: .
    container_name: bandwidth
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./:/app
    ports:
      - "8000:8000"
    # environment:
    #   - SECRET_KEY=test
    #   - DEBUG=True

