# Generated by Django 4.2.9 on 2024-06-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(help_text='Hostname of the server', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the server')),
                ('api_key', models.CharField(max_length=255)),
                ('api_password', models.CharField(max_length=255)),
                ('panel_ipaddress', models.CharField(max_length=255)),
                ('vps_id', models.IntegerField(default=0)),
                ('panel_port', models.IntegerField(default=0)),
                ('telegramAPItoken', models.CharField(max_length=255)),
                ('chat_ID1', models.IntegerField(default=0)),
                ('chat_ID2', models.IntegerField(default=0)),
                ('used_bandwidth_gb', models.CharField(max_length=255)),
                ('limit_bandwidth_gb', models.CharField(max_length=255)),
                ('free_bandwidth_gb', models.CharField(max_length=255)),
            ],
        ),
    ]
